### ISSUE TITLE
Apparent regression in authenticate?method=ext-jwt

### ISSUE THREAD

**Issue by rentallect** [openziti/edge#1037]
Attempts made by browZer to authenticate into Ziti network via `authenticate?method=ext-jwt` currently fail (where they used to succeed).

After some experiments, I believe the current auth failures are due to a regression in edge.  I say this because I can locally reproduce the auth success/failure patten if I move between controller v0.25.9 and v0.25.10

The regression seems to have crept in somewhere between edge 0.21.217 (used in Controller v0.25.9) and edge 0.21.222 (used in Controller v0.25.10)

Only edge 0.21.218 and edge 0.21.221 hit code related to ext-jwt and/or auth in general, so the regression lives in these commits.

I have attached my edge DB.  I can add more detail regarding the various entities (ext-jwt-signer, auth-policy, identity) if needed so just ask :)

[ctrl.db.zip](https://github.com/openziti/edge/files/8845191/ctrl.db.zip)

**Comment by andrewpmartinez** [comment]
Please provide the id of the authenticating identity
