### ISSUE TITLE
Capture and log the IP address of Edge Routers when they create api sessions

### ISSUE THREAD

**Issue by mikegorman-nf** [openziti/edge#1090]
In order to attribute raw network connections (TCP,UDP,QUIC, etc) to Ziti links for performance analysis, there needs to be a method to index the two togther.  Having the IP:PORT information in the logs will allow such attribution and enhance performance management.

**Comment by plorenz** [comment]
We currently only track IP address and not port for sessions created via REST. I'm tracking IP:Port for edge routers, but let me know if that will mess up reporting and if we should update the REST api sessions to also include port. @mikegorman-nf @mguthrie88
