### ISSUE TITLE
integrate with fabric's audit capability

### ISSUE THREAD

**Issue by dovholuknf** [openziti/edge#1223]
add important auditing events to the edge controller. see https://github.com/openziti/fabric/issues/532 for the fabric request

audit things like:
* who changed what service/service policy/made an identity/etc -- important CRUD operations
* coming on/off/panics
* anything else deemed important, critical, 'good to have'

**Comment by plorenz** [comment]
We now have events for CRUD operations, as well as events for many other things (such as sessions). If we need other specific events, we should create individual issues for those.
