### ISSUE TITLE
Active sessions are not being revoked when associated services are deleted

### ISSUE THREAD

**Issue by plorenz** [openziti/edge#131]

**Comment by michaelquigley** [comment]
In the fabric, this is working as originally designed.

I would suggest that we walk towards this in a step-wise manner, and that we ensure the fabric (and edge on top of it) has facilities for removing (terminating) singular active sessions before we go after removing sessions on service removal. Once we're happy with singular session management, we can figure out an approach for service removal.

I would also suggest that we may want to make this behavior flexible at the fabric level. There may be cases where we want to remove services to prevent the creation of new sessions, but want to retain the current active sessions.

**Comment by andrewpmartinez** [comment]
@plorenz is this still an issue?

**Comment by plorenz** [comment]
Duplicate of #93
