### ISSUE TITLE
Panic in edge@v0.24.326/controller/sync_strats/sync_instant.go:194

### ISSUE THREAD

**Issue by plorenz** [openziti/edge#1548]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2c6017e]
goroutine 55254237 [running]:
github.com/openziti/edge/controller/sync_strats.(*InstantStrategy).RouterDisconnected(0xc0026a0c00, 0xc002c453b0)
    github.com/openziti/edge@v0.24.326/controller/sync_strats/sync_instant.go:194 +0x31e
github.com/openziti/edge/controller/env.(*Broker).RouterDisconnected.func1()
    github.com/openziti/edge@v0.24.326/controller/env/broker.go:110 +0x36b
created by github.com/openziti/edge/controller/env.(*Broker).RouterDisconnected
    github.com/openziti/edge@v0.24.326/controller/env/broker.go:105 +0x72
```

**Comment by NetFoundry-Zendesk** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                <div class="panel-body" style="padding: 15px;">
                  <strong>Zendesk:&nbsp;</strong><a href="https://netfoundry.zendesk.com/agent/tickets/11150" target="_blank">11150</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                  Zendesk:&nbsp;<a href="https://netfoundry.zendesk.com/agent/tickets/11150" target="_blank">#11150</a>
                  <div class="pull-right" style="float:right">By: <em>Christian Mark Sioson &lt;mark.sioson@netfoundry.io&gt;</em></div>
                </div>
              </div>
