### ISSUE TITLE
host.v1 and host.v2 are out of sync

### ISSUE THREAD

**Issue by plorenz** [openziti/edge#1616]
host.v1 has listenOptions.connectTimeoutSeconds, host.v2 has listenOptions.connectTimeout.

Should allow both, preferring connectTimeout if available.

**Comment by scareything** [comment]
Just IMO this will be at least slightly confusing to end users, and it isn't clear how this improves the software. I personally think we should have one field.

If we do have one field, IMO it should be `connectTimeoutSeconds`. `connectTimeout` will require tunnelers that aren't written in golang to implement golang's `time.Duration`.

**Comment by plorenz** [comment]
Thinking about this a bit more, I think what we should do is:

1. Add connectTimeout support to c-sdk
2. Document as connectTimeoutSeconds as deprecated, to be removed in x months (or x years)
2. Add migration to migrate connectTimeoutSeconds to connectTimeout
