### ISSUE TITLE
Validate that terminators support edge end-to-end encryption if service requires e2e encyrption

### ISSUE THREAD

**Issue by plorenz** [openziti/edge#297]

**Comment by andrewpmartinez** [comment]
@plorenz unsure if this is still an issue. Confirm w/ comment or closing the issue.

**Comment by plorenz** [comment]
We haven't added any validation. However, since edge installations will likely not be using router termination, rather will be using either the tunneler or xgress_edge_tunnel, all endpoints should support encryption. Given that, I'm going to close this.
