### ISSUE TITLE
Make it easy to figure out how what bindings are valid and what addresses are valid for those bindings

### ISSUE THREAD

**Issue by plorenz** [openziti/edge#298]
Update doc with information about what valid bindings are and what addresses are valid for those bindings.
Add endpoints so that information can be retrieved programmatically and can be used to build user friendly APIs

**Comment by andrewpmartinez** [comment]
@plorenz I assume this is still an issue. I don't recall seeing anything in the changelog about bindings.

**Comment by plorenz** [comment]
> @plorenz I assume this is still an issue. I don't recall seeing anything in the changelog about bindings.

Yes, this is still a nice to have

**Comment by plorenz** [comment]
Low priority. I think existing doc is probably good enough, don't need a REST API. Can re-open if there's user demand for it.
