### ISSUE TITLE
ziti-tunnel configurable IP range for DNS services

### ISSUE THREAD

**Issue by smilindave26** [openziti/edge#338]
169.254/16 isn't routable in some instances, notably in Microsoft's MEC. 

Two things:
1) Change the default IP range to 100.64/10 (which *should* be routable), and
2) Make the IP range configurable (e.g., via command-line switch(es)

**Comment by dovholuknf** [comment]
The config file already allows for you to specify the ip and mask. Edit the config.json file at 

```C:\Windows\System32\config\systemprofile\AppData\Roaming\NetFoundry\config.json```

There are two fields TunIpv4 and TunIpv4Mask that can be set to assign the range to use for the tun and subsequent services
