### ISSUE TITLE
Possible to create un-enrollable Identity resource

### ISSUE THREAD

**Issue by rentallect** [openziti/edge#359]
Doing a POST to the `/identities` endpoint with the following payload:

```
  {
    "isAdmin": false,
    "name": name,
    "type": "User"
  }

```
will successfully create an identity, but the entity will have an empty `enrollment` field, making it impossible to subsequently facilitate an enrollment of the identity.

The `enrollment` field should be required during creation.

**Comment by andrewpmartinez** [comment]
This was intentional. It is possible to create identities, provision them w/ roles, and allow enrollment at a later date.
