### ISSUE TITLE
ziti-tunnel: improve packet connection state management

### ISSUE THREAD

**Issue by ekoby** [openziti/edge#370]
current implementation may leave tcp peer hanging -- connection is removed before the late stages of TCP shutdown is processed

TCP State transitions happen inside conn.Read() which means that once it returns io.EOF no more packet processing can take place.

**Comment by andrewpmartinez** [comment]
@scareything can you confirm if this is still an issue? Confirm by commenting or closing.

**Comment by ekoby** [comment]
closing for age
