### ISSUE TITLE
svcpoll needs to do a deep compare to see if service has been updated

### ISSUE THREAD

**Issue by smilindave26** [openziti/edge#385]
openziti/edge/tunnel/intercept/svcpoll.go

currently only checking if services have been added or deleted.  needs to inspect for changes in service config (e.g.,  hostname/ip, port to intercept has changed)

Update, after I looked more closely at the code:

- hosted services do not query/get new _dial_ config if that had changed

**Comment by ekoby** [comment]
dup https://github.com/openziti/ziti/issues/170

**Comment by scareything** [comment]
We definitely should use the service update callback. To be clear though I don't believe this is a dup of openziti/ziti#170. 170 is talking about newly added services not being picked up - a situation that I have seen with Skip in a MOP-managed environment.

**Comment by ekoby** [comment]
> We definitely should use the service update callback. To be clear though I don't believe this is a dup of [openziti/ziti#170](https://github.com/openziti/ziti/issues/170). 170 is talking about newly added services not being picked up - a situation that I have seen with Skip in a MOP-managed environment.

that could be due to the way service creation is processed by the MOP. I imagine the sequence is:
- MOP: service is created and assigned a role
- tunnel picks up service via polling
- MOP: adds config
- at this point tunnel knows about the service but won't react to config change. ironically more frequent polling makes this more likely to occur

**Comment by plorenz** [comment]
note:  openziti/ziti#170 has been resolved. Should we leave this open?

**Comment by andrewpmartinez** [comment]
@smilindave26 per @plorenz 's comment in 2/8, can we close this now?

**Comment by smilindave26** [comment]
Yes, looks like this has been addresses along the way...
