### ISSUE TITLE
add API to request all edge routers for identity

### ISSUE THREAD

**Issue by ekoby** [openziti/edge#484]
`/current-identity/edge-routers` or `/current-api-session/edge-routers` would return all edge routers that an identity has access to based on applicable Edge Router Policies.

The returned set is expected to be a superset of edge routers returned in sessions.

**Comment by andrewpmartinez** [comment]
Provide:

- edge router advertised address
- edge router status 

As a note to myself this is a list of all edge routers the client could connect to.
