### ISSUE TITLE
Terminators with edge or tunnel binding should not be editable from the REST API

### ISSUE THREAD

**Issue by plorenz** [openziti/edge#522]
@andrewpmartinez suggested making them system components (and introducing the notion of system components)

**Comment by andrewpmartinez** [comment]
I think this is resolved. @plorenz  confirm by closing or commenting.

**Comment by plorenz** [comment]
> I think this is resolved. @plorenz confirm by closing or commenting.

We now have system entities, but edge terminators aren't marked as system entities yet. The main reason I haven't done it yet is because I wasn't sure if we needed a way to do manual cleanup of those entities. We might need some other way to GC edge and tunnel terminators.
