### ISSUE TITLE
The system property should be visible from the REST API

### ISSUE THREAD

**Issue by plorenz** [openziti/edge#614]
Need to figure out if we want to expose this for all entities or just the ones that use it for now (edge router policy)

**Comment by Russell-Allen** [comment]
I assume both identity and edge router policy could have the system property.

I don't know if this is accurate, but I am thinking of a "system" entity as: _any entity who's life cycle (creation, update, delete) is managed indirectly via another entity, or entirely managed by Ziti internal processes._

If I recall correctly, doesn't Ziti automatically create some terminator entities?  Wouldn't they fall under this definition of a "system" entity?

**Comment by plorenz** [comment]
Released under 0.19.9. Closing

**Comment by plorenz** [comment]
> I assume both identity and edge router policy could have the system property.
> 
> I don't know if this is accurate, but I am thinking of a "system" entity as: _any entity who's life cycle (creation, update, delete) is managed indirectly via another entity, or entirely managed by Ziti internal processes._
> 
> If I recall correctly, doesn't Ziti automatically create some terminator entities? Wouldn't they fall under this definition of a "system" entity?

System entity here has a specific functional meaning, which is 'only the system can create/updated/delete this entity'. That is true for the edge router policies. It's not true for router identities, since those can be updated by administrators (mostly to edit role attributes). It's also not currently true for system created terminators, since we let admins delete those. We may at some point mark those as system as well and not allow them to be deleted by admins. At that point we'd also expose the system flag there.
