### ISSUE TITLE
Service identity list does not respect pagination

### ISSUE THREAD

**Issue by andrewpmartinez** [openziti/edge#641]
*Experienced*

`GET services/123456/identities?limit=500&offset=20` doesn't seem to work. Always uses offset=0 limit=10

*Expected*

Offset and limit properties to actually work.

*Reproduction*

1) request services list
2) find a service with some identities
3) attempt to use offset and limit

**Comment by plorenz** [comment]
This works:

**Comment by andrewpmartinez** [comment]
I was using the REST API directly and I saw this issue. 

`{{controller-host}}/services/P-eLUQug-/identities?limit=2&offset=20`

```
        "pagination": {
            "limit": 10,
            "offset": 0,
            "totalCount": 697
        }
```

**Comment by andrewpmartinez** [comment]
Talking w/ @plorenz this turns out to be an interesting issue.

1) offset/limit can be supplied in the `filter` parameter which works great, the separate values don't
2) most of the SDKs and external integrations are using the separate limit/offset parameters
3) some internal tooling (`ziti`) is playing the limit/offset in the `filter` parameter

Eliminating one or the other causes different pains. Leaving two ways to specify them means this bug must be resolved but is the path of least resistance.
