### ISSUE TITLE
CA auto-enrollment ignores device provided name

### ISSUE THREAD

**Issue by ekoby** [openziti/edge#774]
the payload provided during enrollment call is ignored

`{"name":"EK-auto-1"}`

found while implementing name option for  `ziti-edge-tunnel` and tested with `ziti-tunnel` and `ziti edge enroll`

**Comment by andrewpmartinez** [comment]
CA's support an identity naming format (`identityNameFormat`). If one isn't supplied the default is used: `[caName] - [commonName]` as suggested by Robert C.

`identityNameFormat` also supports the following replacements:

- [caName] - replaced with the CA's name
- [caId] - replaced with the CA's id
- [commonName] - replaced with the common name of the enrolling certificate
- [requestedName] - replaced with  the name requested by the enrolling identity
- [identityId] - replaced with the id of the resulting identity
